name: Java CI with Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-test-docker:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v6

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3. Build and test Java application
      - name: Build and Test
        run: mvn clean test

      # 4. Package application
      - name: Package Application
        run: mvn clean package -DskipTests

      # 5. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jenkins-java-project1:latest .

      # 7. Push Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/jenkins-java-project1:latest
